export const fakeEmails = [
  {
    userId: '2018-00004',
    fullName: 'Bob Smith',
    email: 'bob.smith@example.com',
    college: 'College of Sciences',
    dateCreated: '2023-01-04',
  },
  {
    userId: '2018-00005',
    fullName: 'Eva Martinez',
    email: 'eva.martinez@example.com',
    college: 'College of Sciences',
    dateCreated: '2023-01-05',
  },
  {
    userId: '2018-00006',
    fullName: 'Michael Brown',
    email: 'michael.brown@example.com',
    college: 'College of Engineering',
    dateCreated: '2023-01-06',
  },
  {
    userId: '2018-00007',
    fullName: 'Sophia Davis',
    email: 'sophia.davis@example.com',
    college: 'College of Engineering',
    dateCreated: '2023-01-07',
  },
  {
    userId: '2018-00008',
    fullName: 'Daniel Wilson',
    email: 'daniel.wilson@example.com',
    college: 'College of Engineering',
    dateCreated: '2023-01-08',
  },
  {
    userId: '2018-00009',
    fullName: 'Olivia Lee',
    email: 'olivia.lee@example.com',
    college: 'College of Engineering',
    dateCreated: '2023-01-09',
  },
  {
    userId: '2018-00010',
    fullName: 'Matthew Taylor',
    email: 'matthew.taylor@example.com',
    college: 'College of Sciences',
    dateCreated: '2023-01-10',
  },
  {
    userId: '2018-00011',
    fullName: 'Isabel Rodriguez',
    email: 'isabel.rodriguez@example.com',
    college: 'College of Sciences',
    dateCreated: '2023-01-11',
  },
  {
    userId: '2018-00012',
    fullName: 'Andrew Turner',
    email: 'andrew.turner@example.com',
    college: 'College of Engineering',
    dateCreated: '2023-01-12',
  },
  {
    userId: '2018-00013',
    fullName: 'Emma Garcia',
    email: 'emma.garcia@example.com',
    college: 'College of Arts and Sciences',
    dateCreated: '2023-01-13',
  },
];
