export const fakeStudents = [
  {
    userId: '2018-00001',
    fullName: 'John Doe',
    firstName: 'John',
    middleName: 'Robert',
    lastName: 'Doe',
    yearLevel: '3',
    program: 'BSCS',
    status: 'Regular',
    college: 'College of Engineering',
  },
  {
    userId: '2018-00002',
    fullName: 'Jane Doe',
    firstName: 'Jane',
    middleName: 'Elizabeth',
    lastName: 'Doe',
    yearLevel: '2',
    program: 'BSMath',
    status: 'Irregular',
    college: 'College of Arts and Sciences',
  },
  {
    userId: '2018-00003',
    fullName: 'Alice Johnson',
    firstName: 'Alice',
    middleName: 'Marie',
    lastName: 'Johnson',
    yearLevel: '4',
    program: 'BSPhysics',
    status: 'Regular',
    college: 'College of Arts and Sciences',
  },
  {
    userId: '2018-00004',
    fullName: 'Bob Smith',
    firstName: 'Bob',
    middleName: 'William',
    lastName: 'Smith',
    yearLevel: '1',
    program: 'BSBiology',
    status: 'Regular',
    college: 'College of Arts and Sciences',
  },
  {
    userId: '2018-00005',
    fullName: 'Eva Martinez',
    firstName: 'Eva',
    middleName: 'Sophia',
    lastName: 'Martinez',
    yearLevel: '2',
    program: 'BSChemistry',
    status: 'Irregular',
    college: 'College of Arts and Sciences',
  },
  {
    userId: '2018-00006',
    fullName: 'Michael Brown',
    firstName: 'Michael',
    middleName: 'James',
    lastName: 'Brown',
    yearLevel: '3',
    program: 'BSElectricalEngineering',
    status: 'Regular',
    college: 'College of Engineering',
  },
  {
    userId: '2018-00007',
    fullName: 'Sophia Davis',
    firstName: 'Sophia',
    middleName: 'Grace',
    lastName: 'Davis',
    yearLevel: '4',
    program: 'BSMechanicalEngineering',
    status: 'Irregular',
    college: 'College of Engineering',
  },
  {
    userId: '2018-00008',
    fullName: 'Daniel Wilson',
    firstName: 'Daniel',
    middleName: 'Alexander',
    lastName: 'Wilson',
    yearLevel: '1',
    program: 'BSCivilEngineering',
    status: 'Regular',
    college: 'College of Engineering',
  },
  {
    userId: '2018-00009',
    fullName: 'Olivia Lee',
    firstName: 'Olivia',
    middleName: 'Rose',
    lastName: 'Lee',
    yearLevel: '2',
    program: 'BSCS',
    status: 'Regular',
    college: 'College of Engineering',
  },
  {
    userId: '2018-00010',
    fullName: 'Matthew Taylor',
    firstName: 'Matthew',
    middleName: 'Christopher',
    lastName: 'Taylor',
    yearLevel: '3',
    program: 'BSMath',
    status: 'Irregular',
    college: 'College of Arts and Sciences',
  },
  {
    userId: '2018-00011',
    fullName: 'Isabel Rodriguez',
    firstName: 'Isabel',
    middleName: 'Maria',
    lastName: 'Rodriguez',
    yearLevel: '4',
    program: 'BSChemistry',
    status: 'Regular',
    college: 'College of Arts and Sciences',
  },
  // ... (continue with more students)
];
