export const undergradGrades = [
  {
    subjectCode: 'GEIT 839-1',
    subjectTitle: 'Strategic Management',
    units: '3.0',
    grade: '1.0',
    completion: '#',
    remarks: 'Passed',
  },
  {
    subjectCode: 'CS101',
    subjectTitle: 'Introduction to Computer Science',
    units: '4.0',
    grade: '2.5',
    completion: '#',
    remarks: 'Passed',
  },
  {
    subjectCode: 'MATH200',
    subjectTitle: 'Calculus II',
    units: '3.0',
    grade: '3.0',
    completion: '#',
    remarks: 'Passed',
  },
  {
    subjectCode: 'PHYS101',
    subjectTitle: 'Physics I',
    units: '4.0',
    grade: '2.0',
    completion: '#',
    remarks: 'Passed',
  },
  {
    subjectCode: 'CHEM200',
    subjectTitle: 'Organic Chemistry',
    units: '3.0',
    grade: '3.5',
    completion: '#',
    remarks: 'Passed',
  },
  {
    subjectCode: 'ENG101',
    subjectTitle: 'English Composition',
    units: '3.0',
    grade: '1.5',
    completion: '#',
    remarks: 'Passed',
  },
  {
    subjectCode: 'HIST202',
    subjectTitle: 'World History',
    units: '3.0',
    grade: '2.75',
    completion: '#',
    remarks: 'Passed',
  },
  {
    subjectCode: 'ART103',
    subjectTitle: 'Introduction to Art',
    units: '2.0',
    grade: '3.0',
    completion: '#',
    remarks: 'Passed',
  },
  {
    subjectCode: 'PHIL201',
    subjectTitle: 'Philosophy',
    units: '3.0',
    grade: '2.0',
    completion: '#',
    remarks: 'Passed',
  },
  {
    subjectCode: 'ECON301',
    subjectTitle: 'Microeconomics',
    units: '3.0',
    grade: '1.5',
    completion: '#',
    remarks: 'Passed',
  },
];
