import * as z from 'zod';

export const StudentSchema = z.object({
  studentId: z.string({}),
  firstName: z.string({}),
  middleName: z.string({}),
  lastName: z.string({}),
  nameExtension: z.string({}),
  maidenName: z.string({}),
  birthDate: z.string({}),
  birthPlace: z.string({}),
  birthSex: z.string({}),
  genderIdentity: z.string({}),
  civilStatus: z.string({}),
  phoneNum: z.string({}),
  emailAddress: z.string({}),
  entryYear: z.string({}),
  program: z.string({}),
  studentType: z.string({}),
  block: z.string({}),
  college: z.string({}),
  regCode: z.string({}),
  yearLevel: z.string({}),
  scholarsticStatus: z.string({}),
  enrolled: z.string({}),
  streetAddress: z.string({}),
  province: z.string({}),
  zipCode: z.string({}),
});

export const StudentSchemaDefaultValues = {
  studentId: '',
  firstName: '',
  middleName: '',
  lastName: '',
  nameExtension: '',
  maidenName: '',
  birthDate: '',
  birthPlace: '',
  genderIdentity: '',
  birthSex: '',
  civilStatus: '',
  phoneNum: '',
  emailAddress: '',
  entryYear: '',
  program: '',
  studentType: '',
  block: '',
  college: '',
  regCode: '',
  yearLevel: '',
  scholarsticStatus: '',
  enrolled: '',
  streetAddress: '',
  province: '',
  zipCode: '',
};
