import { ColorSchemeScript } from '@mantine/core';
// ! Mantine Imports
import '@mantine/core/styles.css';
import { Inter } from 'next/font/google';

import Providers from '../../../components/component/providers';
import AuthProvider from '@/components/component/auth';
import '../../globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function PublicRouteRootLayoutLogin({ children }) {
    return (
        <html lang='en'>
            <head>
                <ColorSchemeScript />
            </head>
            <body className={inter.className}>
                <Providers>
                    <AuthProvider accessLevel="public">
                        {children}
                    </AuthProvider>
                </Providers>
            </body>
        </html>
    );
}
