name: Capture Vercel Preview URL and Update Azure Redirect URIs

on:
  push:

jobs:
  capture_vercel_preview_url:
    name: Capture Vercel Preview URL
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2

      - name: Sleep for 30 seconds
        run: sleep 30

      - name: vercel-preview-url
        uses: zentered/vercel-preview-url@v1.1.9
        id: vercel_preview_url
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          vercel_project_id: 'prj_3hOQM4SDgkaItQrnmDzZio4KkRKZ'

      - name: Install Xvfb
        run: sudo apt-get install -y xvfb

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium chromedriver_autoinstaller pyvirtualdisplay

      - name: Run Python script
        run: python .github/scripts/azure_selenium.py ${{ secrets.AZURE_USERNAME }} ${{ secrets.AZURE_PASSWORD }} ${{ steps.vercel_preview_url.outputs.preview_url }}
