name: Capture Vercel Preview URL and Update Azure Redirect URIs

on:
 issue_comment:
  types: [edited]

jobs:
 capture_vercel_preview_url:
  name: Capture Vercel Preview URL
  runs-on: "ubuntu-latest"
  steps:
    - uses: actions/checkout@v2

    - uses: aaimio/vercel-preview-url-action@v2.2.0
      id: vercel_preview_url
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Run Python script
      run: python .github/scripts/azure_selenium.py ${{ secrets.AZURE_USERNAME }} ${{ secrets.AZURE_PASSWORD }} ${{ steps.vercel_preview_url.outputs.vercel_preview_url }}
