name: Capture Vercel Preview URL and Update Azure Redirect URIs

on:
  push:

jobs:
  capture_vercel_preview_url:
    name: Capture Vercel Preview URL
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checking out repository
        uses: actions/checkout@v3

      - name: Sleep for 30 seconds
        run: sleep 30

      - name: vercel-preview-url
        uses: zentered/vercel-preview-url@v1.1.9
        id: vercel_preview_url
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          vercel_project_id: 'prj_3hOQM4SDgkaItQrnmDzZio4KkRKZ'

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installing package list
        run: apt list --installed

      - name: Removing previous chrome instances on runner
        run: sudo apt purge google-chrome-stable

      # Need to fetch reqs if needed
      - name: Installing all necessary packages
        run: pip install chromedriver-autoinstaller selenium pyvirtualdisplay

      - name: Install xvfb
        run: sudo apt-get install xvfb

      - name: Run Python script
        run: python .github/scripts/azure_selenium.py ${{ secrets.AZURE_USERNAME }} ${{ secrets.AZURE_PASSWORD }} ${{ steps.vercel_preview_url.outputs.preview_url }}
